image: golang:latest

variables:
  REPO_NAME: gitlab.com/Prophesians/swivel-server

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
  - curl https://glide.sh/get | sh
  - glide install

stages:
    - build

compile:
    stage: build
    script:
      - make build
